language: ruby
script: echo hi
sudo: false
dist: trusty
matrix:
  include:
    - addons:
        packages:
          apt:
            - gcc-4.8
    - addons:
        packages:
          apt:
            - g++-4.8
