language: ruby
script: echo hi
sudo: false
dist: trusty
matrix:
  include:
    - env: FOO=1
      services:
       - mongodb
      addons:
        packages:
          - gcc-4.8
    - env: FOO=2
      services:
        - elasticsearch
      addons:
        packages:
          - g++-4.8
